language: node_js

node_js:
  - "10.6"

env:
  - QMULUS_MONGO_URI=mongodb://localhost:27017/qmulus

cache:
  directories:
    - node_modules

services:
  - mongodb

install:
  - npm install

script:
  - npm test
  - npm run lint

after_success: npm run coverage

sudo: false
