name: Deploy PROD

on:
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.6.x'

    - name: lint and test
      continue-on-error: false
      run: |
        npm install
        npm run lint
        npm run build --if-present
        npm test
      env:
        CI: true

    - name: Install pm2
      run: npm install -g pm2

    - name: Run pm2 production deploy script
      env:
        PM2_HOSTS: ${{ secrets.PM2_HOSTS }}
        HOST_QMULUS_TOR_01: ${{ secrets.HOST_QMULUS_TOR_01 }}
      run: |
        echo "Starting pm2 prod deploy"
        pm2 deploy ecosystem.config.js production --force

